version: '3.0' # specify docker-compose version

# Define the services/containers to be run
services:
 client:
   build: ./client
   ports:
     - "4200:4200"
   links:
     - server
   networks:
     - mongo-net
 server:
   build: ./server
   ports:
     - "8080:8080"
   environment:
     - MONGO_URL=mongodb://admin:admin@mymongodb:27017/mydata?authSource=admin
   depends_on:
     - mongo
   networks:
     - mongo-net
 mongo:
   image: mongo:latest
   container_name: "mongo"
   ports:
     - "27017:27017"
   volumes:
     - ~/mongodata:/data/db
   command: mongod --auth
   networks:
     - mongo-net

networks:
 mongo-net:
   driver: bridge