# Base image with Node.js
FROM node:alpine

# Create app directory
WORKDIR /usr/src/app

#Expose Argument for setting MONGO_HOST
ARG MONGO_HOST=mongodev

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

# Install any needed packages
RUN npm install

# Bundle app source
COPY . .

# Expose port 8080
EXPOSE 8080

# Run the npm start command
CMD [ "npm", "start" ]